<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Curriculo</title>
        <link rel="stylesheet" href="index.css">
    </head>

    <body>
    <main>
        <?php
            $login 

        ?>
        <p><a href="javascript:history.go(-1)">Voltar para página anterior</a></p>
    </main>

        <form action="">
                <h1 id="linha">__</h1><h5>
                <div class="input">
                    <label for="nome">Nome:</label><br>
                    <input type="text" id="nome" required maxlength="18"><br>
                </div>

                <div class="input">
                    <label for="email">Email:</label> <br>
                    <input type="email" id="emai1l" required> <br>
                </div>

                <div class="input">
                    <label for="senha">Senha:</label><br>
                    <input type="password"  id="senha" required minlength="8"><br>
                </div>

                <div class="input">
                    <label for="senha">Confirme a senha:</label><br>
                    <input type="password"  id="senha" required minlength="8"><br>
                </div></h5> 
                <br>
                <div id="button">
                    <button type="button" class="btn btn-light">Enviar</a></button>
                    <button type="reset" class="btn btn-light">Limpar</button>
                </div>

    </body>
    </html> 
